### ISSUE TITLE
PRACTICA 7_MARIA JOSE LOPEZ LEYVA

### ISSUE THREAD

**Issue by MariaJose-10** [SistemasTecTlaxiaco/conexion-bases-de-datos-equipo-topicos-avanzados#1]
[TOPICOS AVANZADOS_PRACTICA 7_MARIA JOSE LOPEZ LEYVA.pdf](https://github.com/SistemasTecTlaxiaco/conexion-bases-de-datos-equipo-topicos-avanzados/files/8664445/TOPICOS.AVANZADOS_PRACTICA.7_MARIA.JOSE.LOPEZ.LEYVA.pdf)
[ezyzip.zip](https://github.com/SistemasTecTlaxiaco/conexion-bases-de-datos-equipo-topicos-avanzados/files/8664489/ezyzip.zip)

**Comment by NoeliaGlez** [comment]
20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
