### ISSUE TITLE
Práctica 7 Conexión de Bases de Datos

### ISSUE THREAD

**Issue by Litzy-lopez4** [SistemasTecTlaxiaco/conexion-bases-de-datos-equipo-topicos-avanzados#2]
[Conexion de base de base de datos.zip](https://github.com/SistemasTecTlaxiaco/conexion-bases-de-datos-equipo-topicos-avanzados/files/8664600/Conexion.de.base.de.base.de.datos.zip)
[Practica 7.pdf](https://github.com/SistemasTecTlaxiaco/conexion-bases-de-datos-equipo-topicos-avanzados/files/8664603/Practica.7.pdf)

**Comment by NoeliaGlez** [comment]
20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
