### ISSUE TITLE
Practica_ConexionBaseDeDatos_JudithReynaCruzSantiago_4US

### ISSUE THREAD

**Issue by JudithReynaCS** [SistemasTecTlaxiaco/conexion-bases-de-datos-equipo-topicos-avanzados#3]
[BASE DE DATOS_JUDITHREYNACRUZSANTIAGO.zip](https://github.com/SistemasTecTlaxiaco/conexion-bases-de-datos-equipo-topicos-avanzados/files/8664666/BASE.DE.DATOS_JUDITHREYNACRUZSANTIAGO.zip)
[Practica_CBD_JudithReynaCruzSantiago.pdf](https://github.com/SistemasTecTlaxiaco/conexion-bases-de-datos-equipo-topicos-avanzados/files/8664669/Practica_CBD_JudithReynaCruzSantiago.pdf)

**Comment by NoeliaGlez** [comment]
20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
